apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ytsrtgen.fullname" . }}
  labels:
    {{- include "ytsrtgen.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ytsrtgen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ytsrtgen.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LISTEN_ADDR
              value: ":{{ .Values.ports.containerPort }}"
          ports:
            - name: http
              containerPort: {{ .Values.ports.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
