apiVersion: v1
kind: Service
metadata:
  name: {{ include "ytsrtgen.fullname" . }}
  labels:
    {{- include "ytsrtgen.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.ports.servicePort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ytsrtgen.selectorLabels" . | nindent 4 }}
