image:
  repository: aijutsudev/ytsrtgen
  tag: 20260518-403b048a
  pullPolicy: IfNotPresent

ports:
  containerPort: 8080
  servicePort: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
