image:
  repository: aijutsudev/ytsrtgen
  tag: 20260518-403b048a
  pullPolicy: IfNotPresent

ports:
  containerPort: 8080
  servicePort: 80

resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
