image:
  repository: ytsrtgen
  tag: 20260518-cc1b1d75
  pullPolicy: IfNotPresent

ports:
  containerPort: 8080
  servicePort: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
